title: Zeke Baker
description: Software Engineer
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://clydehobart.github.io" # change this to the base hostname & protocol for your site

google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%Y-%m-%d"

theme: # leave it empty

# Build settings
# markdown: kramdown

# social
author: "Zeke Baker"
# image: /thumbnail-jumbo.png
github:
  owner_name: "Zeke Baker"
  owner_url: https://github.com/ClydeHobart
# twitter:
#   username: lorepirri

plugins:
  - jekyll
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['code-samples', 'now', 'about']
# header_page_refs: ['now', 'about', 'contact']
